Fixed issue with conditional content in customer email
UKHomeOffice/eta pull request #22
Opened 2023-10-12 14:54 UTC by mislam987

PR for the conditional content fix on customer emails.

2023-10-13 15:37 UTC, Rhodine-orleans-lindsay requested changes
looks good just a couple of changes

2023-10-13 15:37 UTC, Rhodine-orleans-lindsay commented on apps/eta/emails/caseworker.html
> +  {{label}}
Did you mean to keep this in?

2023-10-13 15:37 UTC, Rhodine-orleans-lindsay commented on apps/eta/behaviours/customer-email.js
> +          label: model['what-is-your-question-about'] === 'I have not received a confirmation email' ||
I think needs to be reverted?

2023-10-13 15:51 UTC, mislam987 commented on apps/eta/emails/caseworker.html
> +  {{label}}
Removed the extra property.

2023-10-13 15:52 UTC, mislam987 commented on apps/eta/behaviours/customer-email.js
> +          label: model['what-is-your-question-about'] === 'I have not received a confirmation email' ||
Reverted back to value.

2023-10-13 15:54 UTC, mislam987 commented on apps/eta/views/confirmation.html
> +<title>{{#t}}Question sent - Ask a question about ETA{{/t}} – GOV.UK</title>
Included the whole title to keep it the same as in the wireframe. Also kept the title in the html page to be consistent with the other pages.

2023-10-13 15:57 UTC, Rhodine-orleans-lindsay approved these changes
lgtm

2023-10-16 11:55 UTC, shamiluwais approved these changes

2023-10-16 14:39 UTC, merged